name: CI

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [nightly, stable]
    steps:
    - uses: actions/checkout@v3
    - name: install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt,clippy
    - name: info
      run: rustc --version
    - name: check
      run: cargo check --verbose
    - name: test
      run: cargo test --verbose --workspace
    - name: fmt
      run: cargo fmt --verbose --all -- --check
    - name: clippy
      run: cargo clippy --workspace -- -D clippy::all
